gRPC based SQL endpoint + readline based command-line.
Client:

    pranadb> use test;
    error: no such schema "test"
    pranadb> create schema test;
    pranadb> create source sensor_readings( sensor_id big int, location varchar, temperature double, primary key (sensor_id));
    pranadb> create materialized view test select sensor_id, max(temperature) from test.sensor_readings where location='wincanton' group by sensor_id;
    pranadb> select * from test;
    pranadb>

Server:

    2021-07-20 13:37:24.098207 I | Starting PranaDB server on 127.0.0.1:6584
    2021-07-20 13:37:25.589575 I | New SQL session started
    2021-07-20 13:37:28.765377 I | exec: use test;
    2021-07-20 13:37:31.699752 I | exec: create schema test;
    2021-07-20 13:37:31.700016 I | Switched to schema: test
    2021-07-20 13:37:35.537323 I | exec: create source sensor_readings( sensor_id big int, location varchar, temperature double, primary key (sensor_id));
    2021-07-20 13:37:35.538688 I | creating source sensor_readings on node 0
    2021-07-20 13:37:38.839649 I | exec: create materialized view test select sensor_id, max(temperature) from test.sensor_readings where location='wincanton' group by sensor_id;
    2021-07-20 13:37:38.841498 I | creating mv test on node 0
    2021-07-20 13:37:42.426800 I | exec: select * from test;
    2021-07-20 13:37:42.426886 I | Executing query select * from test;
    2021-07-20 13:37:42.427841 I | Executing remote query on shardID 9
    2021-07-20 13:37:42.427860 I | Executing remote query on shardID 5
    2021-07-20 13:37:42.427876 I | Executing remote query on shardID 4
    2021-07-20 13:37:42.427893 I | Executing remote query on shardID 6
    2021-07-20 13:37:42.427906 I | Executing remote query on shardID 3
    2021-07-20 13:37:42.427949 I | Executing remote query on shardID 1
    2021-07-20 13:37:42.427968 I | Executing remote query in engine select * from test; query id 0-1-3 shardID 3
    2021-07-20 13:37:42.427980 I | Didn't find query in map, so creating a new dag
    2021-07-20 13:37:42.427988 I | Executing query select * from test;
    2021-07-20 13:37:42.428011 I | Executing remote query in engine select * from test; query id 0-1-9 shardID 9
    2021-07-20 13:37:42.428043 I | Didn't find query in map, so creating a new dag
    2021-07-20 13:37:42.428050 I | Executing query select * from test;
    2021-07-20 13:37:42.428057 I | Executing remote query in engine select * from test; query id 0-1-1 shardID 1
    2021-07-20 13:37:42.428071 I | Didn't find query in map, so creating a new dag
    2021-07-20 13:37:42.428079 I | Executing query select * from test;
    2021-07-20 13:37:42.428109 I | Executing remote query in engine select * from test; query id 0-1-5 shardID 5
    2021-07-20 13:37:42.428123 I | Didn't find query in map, so creating a new dag
    2021-07-20 13:37:42.428130 I | Executing query select * from test;
    2021-07-20 13:37:42.428485 I | Got 0 rows from table 101 and shard 1
    2021-07-20 13:37:42.428505 I | Pull query select * from test; on node 0 and shard 1 returning 0 rows
    2021-07-20 13:37:42.428514 I | Got 0 rows from table 101 and shard 9
    2021-07-20 13:37:42.428531 I | Pull query select * from test; on node 0 and shard 9 returning 0 rows
    2021-07-20 13:37:42.428553 I | Got 0 rows from table 101 and shard 3
    2021-07-20 13:37:42.428568 I | Pull query select * from test; on node 0 and shard 3 returning 0 rows
    2021-07-20 13:37:42.428577 I | Executing remote query on shardID 2
    2021-07-20 13:37:42.428603 I | Executing remote query in engine select * from test; query id 0-1-2 shardID 2
    2021-07-20 13:37:42.428614 I | Didn't find query in map, so creating a new dag
    2021-07-20 13:37:42.428620 I | Executing query select * from test;
    2021-07-20 13:37:42.428641 I | Executing remote query in engine select * from test; query id 0-1-4 shardID 4
    2021-07-20 13:37:42.428653 I | Didn't find query in map, so creating a new dag
    2021-07-20 13:37:42.428659 I | Executing query select * from test;
    2021-07-20 13:37:42.428677 I | Executing remote query on shardID 7
    2021-07-20 13:37:42.428701 I | Executing remote query in engine select * from test; query id 0-1-7 shardID 7
    2021-07-20 13:37:42.428711 I | Didn't find query in map, so creating a new dag
    2021-07-20 13:37:42.428716 I | Executing query select * from test;
    2021-07-20 13:37:42.428724 I | Executing remote query in engine select * from test; query id 0-1-6 shardID 6
    2021-07-20 13:37:42.428733 I | Didn't find query in map, so creating a new dag
    2021-07-20 13:37:42.428738 I | Executing query select * from test;
    2021-07-20 13:37:42.428794 I | Got 0 rows from table 101 and shard 2
    2021-07-20 13:37:42.428803 I | Pull query select * from test; on node 0 and shard 2 returning 0 rows
    2021-07-20 13:37:42.428839 I | Executing remote query on shardID 8
    2021-07-20 13:37:42.428853 I | Executing remote query in engine select * from test; query id 0-1-8 shardID 8
    2021-07-20 13:37:42.428858 I | Didn't find query in map, so creating a new dag
    2021-07-20 13:37:42.428866 I | Executing query select * from test;
    2021-07-20 13:37:42.428883 I | Got 0 rows from table 101 and shard 5
    2021-07-20 13:37:42.428894 I | Pull query select * from test; on node 0 and shard 5 returning 0 rows
    2021-07-20 13:37:42.428900 I | Executing remote query on shardID 0
    2021-07-20 13:37:42.428919 I | Executing remote query in engine select * from test; query id 0-1-0 shardID 0
    2021-07-20 13:37:42.428925 I | Didn't find query in map, so creating a new dag
    2021-07-20 13:37:42.428931 I | Got 0 rows from table 101 and shard 4
    2021-07-20 13:37:42.428943 I | Pull query select * from test; on node 0 and shard 4 returning 0 rows
    2021-07-20 13:37:42.428949 I | Got 0 rows from table 101 and shard 6
    2021-07-20 13:37:42.428957 I | Pull query select * from test; on node 0 and shard 6 returning 0 rows
    2021-07-20 13:37:42.428964 I | Got 0 rows from table 101 and shard 7
    2021-07-20 13:37:42.428970 I | Pull query select * from test; on node 0 and shard 7 returning 0 rows
    2021-07-20 13:37:42.428976 I | Executing query select * from test;
    2021-07-20 13:37:42.429043 I | Got 0 rows from table 101 and shard 8
    2021-07-20 13:37:42.429055 I | Pull query select * from test; on node 0 and shard 8 returning 0 rows
    2021-07-20 13:37:42.429152 I | Got 0 rows from table 101 and shard 0
    2021-07-20 13:37:42.429161 I | Pull query select * from test; on node 0 and shard 0 returning 0 rows